from fastapi.testclient import TestClient

from app.core.models import ArchitectureProject
from app.main import app

client = TestClient(app)


def test_sample_endpoint_returns_valid_project() -> None:
    response = client.get("/projects/sample")
    assert response.status_code == 200
    project = ArchitectureProject.model_validate(response.json())
    assert project.id == "sample-2bhk-east"
    assert len(project.rooms) == 8
    assert project.units == "feet"


def test_sample_endpoint_merges_validator_advisories() -> None:
    payload = client.get("/projects/sample").json()
    warning_ids = {w["id"] for w in payload["warnings"]}
    assert "warn-bath-distance" in warning_ids  # curated by the factory
    assert "warn-open-area" in warning_ids  # generated by the validator
